### ISSUE TITLE
403, access forbidden.

### ISSUE THREAD

**Issue by abutaufique** [AFRL-RY/data-unicorn-2008#1]
Hello, I am trying to download the dataset but getting 403, access forbidden. I can perform 
s3cmd --requester-pays ls s3://sdms-unicorn-2008
and see the files. But when I am using "get", I am getting 403 access forbidden error. 

s3cmd --requester-pays get s3://sdms-unicorn-2008/position_text.tar.gz

Please let me know if you have any suggestions. 
Thanks,

**Comment by rovitotv** [comment]
Sorry about the trouble that you are having.....First I had the permissions wrong, now they are correct.  Second the example command had a invalid path and has been corrected in the README.md.  The correct command is:

```
s3cmd --requester-pays get s3://sdms-unicorn-2008/truth/20080816_UNICORN_GPS_Ground_Truth.zip
```
Please let us know if you have additional troubles by re-opening this issue.  Thank you.
