### ISSUE TITLE
Registration/coincidence is slightly off

### ISSUE THREAD

**Issue by JLC7** [AFRL-RY/data-unicorn-2008#10]
I was able to extract some targets; however, a lot of them seem to seem to be slightly shifted between the modalities as in this example. The SAR seems to not be exactly aligned with the target in the EO. Is that expected for the majority of the imagery? Is there a way to address this issue?

![Picture1](https://user-images.githubusercontent.com/17368281/72669397-1709c900-39e6-11ea-9a91-01a4168acaff.png)

Thanks

**Comment by rovitotv** [comment]
Yes it is expected and we have no publicly available method to fix it.
