### ISSUE TITLE
ERROR: S3 error: 403 (Forbidden)

### ISSUE THREAD

**Issue by deepffff** [AFRL-RY/data-unicorn-2008#14]
Hi, I attempt to download data using the command "s3cmd --requester-pays get s3://sdms-unicorn-2008/truth/20080816_UNICORN_GPS_Ground_Truth.zip", but it returns "ERROR: S3 error: 403 (Forbidden)". And I have tried all the commands to access the data, but they all failed. Do you know why and Can you help me with that?

**Comment by rovitotv** [comment]
I am sorry we can't  help you download the data, but you might want to contact AWS support.
