### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by yemu1138178251** [AFRL-RY/data-unicorn-2008#15]
Hello, we purchased data from Unicorn2008 in the past and re labeled it to create the USOD dataset. Now that our results have been published, can we make our USOD dataset public? Does this violate the copyright of Unicorn2008?

**Comment by rovitotv** [comment]
I am not sure what you mean by "purchased".  AWS does charge bandwidth fees to download the data but that is only for bandwidth.  This data set was collected by the US government and is under the public domain, see [copyright information](https://github.com/AFRL-RY/data-unicorn-2008?tab=readme-ov-file#copyright-information).  Public domain is explained on [wikipedia](https://en.wikipedia.org/wiki/Public_domain).  Yes you can make your USOD dataset public!  It would be appropriate, but not required by law, to have a [citation](https://github.com/AFRL-RY/data-unicorn-2008?tab=readme-ov-file#citation) to the data-unicorn-2008 dataset
