### ISSUE TITLE
Raw Phase History Data

### ISSUE THREAD

**Issue by wevonosky** [AFRL-RY/data-unicorn-2008#3]
I would like access to the raw SAR phase history data.

**Comment by rovitotv** [comment]
William,
    After several months you are the only person to ever request the raw SAR phase history.  Unfortunately we can't justify uploading it to the cloud for a single person.  If you put in a data request by contact sdms_help@vdl.afrl.af.mil they will make arrangements to mail you the data.  You will have to send in a 4 TB hard disk and SDMS will fill it up and send it back to you.

**Comment by back2yes** [comment]
Hi, is the raw phase history data still available? (with my own hard drive)
