### ISSUE TITLE
Description of header

### ISSUE THREAD

**Issue by JLC7** [AFRL-RY/data-unicorn-2008#4]
Hello, 

Is there a descriptions of the following header for targets and what each contains somewhere?

`track_point.fileId,track_point.time,track_point.frame,track.id,track_point.id,target_type.name,color.color,track.length,track.width,track_point.x,track_point.y,track_point.latitude,track_point.longitude`

**Comment by JLC7** [comment]
Does track.width and track.length correspond to dimensions of a bounding box around the target? It doesn't seem like it does so I am unsure of what they are? Any clarification would be appreciated.

**Comment by rovitotv** [comment]
We do have a document that describes all the fields but it needs to go through the public release process before we can post it.  Both track.width and track.length are in meters.

**Comment by JLC7** [comment]
That makes a little more sense. However, I've found that length and width of some objects, particularly the majority of planes, seem a little too small <2m in some cases. Would that be expected?

**Comment by JLC7** [comment]
Here is a histogram of the width and height of the plane class: 
![image](https://user-images.githubusercontent.com/17368281/71315301-1a715b00-240e-11ea-96b2-8debb66dfca5.png)

![image](https://user-images.githubusercontent.com/17368281/71315304-3248df00-240e-11ea-8583-43b68159898c.png)

**Comment by rovitotv** [comment]
the only information that is available is in this repo.
