### ISSUE TITLE
Duplicate rows in 20080816_UNICORN_truth_csv.zip

### ISSUE THREAD

**Issue by rzj** [AFRL-RY/data-unicorn-2008#5]
I noticed there are lots of duplicate rows in 20080816_UNICORN_truth_csv.zip.  Do you know what that would be the case?

```
x = pd.read_csv('data/truth/20080816_UNICORN_truth_csv.zip')
x.shape # 12,766,950
x.drop_duplicates().shape # 4,729,685
```

**Comment by rzj** [comment]
Further, I think the number of records in the `track_point` tables of the `wammit_gotcha_v*.db` sqlite files are `[390517, 390517, 390517, 390517, 390517]` which adds up to 1.9M track points.  

How does that reconcile that w/ the 12M rows in `20080816_UNICORN_truth_csv.zip`?

**Comment by JLC7** [comment]
Yes I am also finding about 8 million rows are duplicates. Any reason why that is?

**Comment by rovitotv** [comment]
After some investigation by @CJMenart we have corrected the page and the duplicate records.  Sorry for any confusion.

**Comment by CJMenart** [comment]
FYA we recommend that everyone download the new csv at
https://sdms-unicorn-2008.s3.amazonaws.com/truth/20080816_UNICORN_truth_csv_corrected.zip

In addition to duplicate records, the old csv  contained some out-of-date labels that were likely intended to be removed.
