### ISSUE TITLE
SAR and EO alignment issues

### ISSUE THREAD

**Issue by ezwABC** [AFRL-RY/data-unicorn-2008#6]
I loaded in two of the NITF files (one SAR and one EO) into QGIS (version 3.10). The coordinate systems for the two do not match (are not aligned). Both files were loaded using the GDAL python library. 

I printed out the result of GetProjection() and got the following output for both images:

GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]

Any idea why this is the case? I attached a picture below. 

![github](https://user-images.githubusercontent.com/59093418/71268280-94c0b300-231a-11ea-9dc7-92df0d727932.png)

**Comment by ezwABC** [comment]
Is it possible to get a code snippet (using python + gdal) of obtaining a target (e.g. SUV) from the EO and SAR images?

**Comment by rovitotv** [comment]
I am sorry we can't provide technical support on how to read NITF files.
